---
version: "3"

tasks:
  default:
    cmds:
      - task -l

  start:
    desc: Run Dagster
    deps:
      - build:dagster
    cmds:
      - docker compose --profile dagster up

  start:detached:
    desc: Run Dagster in the background
    deps:
      - build:dagster
    cmds:
      - docker compose --profile dagster up -d

  restart:data_analytics:
    desc: Restart the data analytics workspace
    cmds:
      - docker container restart $(docker ps -aqf "name=data-analytics")

  restart:data_science:
    desc: Restart the data analytics workspace
    cmds:
      - docker container restart $(docker ps -aqf "name=data-science")

  down:
    desc: Stop Dagster
    cmds:
      - docker compose --profile dagster down --remove-orphans

  # Cleaning
  clean:
    desc: Remove cruft and cache files from the project
    cmds:
      - rm -rf .mypy_cache/ **/.pytest_cache/
      - rm -f **/coverage.xml **/.coverage

  # Formatting
  fmt:
    desc: Run formatting on code with black and isort
    deps:
      - build:format
    cmds:
      - docker compose run -- format

  # Test
  test:data-analytics:
    desc: Run data analytics workspace tests
    deps:
      - build:test-data-analytics
    cmds:
      - docker compose run -- data-analytics-test

  test:data-science:
    desc: Run data science workspace tests
    deps:
      - build:test-data-science
    cmds:
      - docker compose run -- data-science-test

  # Build Stages
  build:dagster:
    desc: Build dagster
    cmds:
      - docker compose --profile dagster build

  build:format:
    desc: Build format
    cmds:
      - docker compose build -- format

  build:test-data-analytics:
    desc: Build workspace test
    cmds:
      - docker compose build -- data-analytics-test

  build:test-data-science:
    desc: Build workspace test
    cmds:
      - docker compose build -- data-science-test