---
name: Test

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        run: docker compose run -- format

      - name: Test Data Analytics
        run: docker compose run -- data-analytics-test

      - name: Test Data Science
        run: docker compose run -- data-science-test